[project]
name = "files2md"
version = "0.1.0"
description = "Create markdown from a collection of files."
authors = [
    {name = "Mike Clark", email = "mike.clark.8192@gmail.com"},
]
dependencies = [
    "charset-normalizer>=3.3.2",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
files2md = "files2md.cli:main"

[tool.pdm]
distribution = true
