# Built-in pattern sets, organised by category. Patterns are stored WITHOUT a
# leading "!"; their include/exclude polarity is applied when the pattern chain
# is assembled (cli_impl.build_pattern_chain). See PATTERNS.md for the layered
# model these feed into.

# "Everyday" excludes: low-signal files you almost never want in a dump. They
# are overridable by user --glob patterns, which apply *after* them.
EVERYDAY_EXCLUDE_SETS: dict[str, list[str]] = {
    # Compiled / opaque build artifacts. (Content is also auto-excluded by
    # binary detection; matching here keeps them out of the file listing too.)
    "binary": [
        "*.pyc", "*.pyo", "*.pyd",
        "*.o", "*.obj", "*.a", "*.lib",
        "*.so", "*.dll", "*.dylib",
        "*.exe", "*.bin", "*.class",
        "*.apk", "*.app", "*.appx", "*.appxbundle", "*.ipa", "*.msi", "*.msix",
        "*.dump", "*.dmp",
        "*.suo", "*.pdb", "*.idb", "*.ilk", "*.exp",
        "*.pch", "*.ipch", "*.sbr", "*.tlb", "*.tlh", "*.tli",
    ],
    # Version-control internals.
    "vcs": [
        ".git/", ".svn/", ".hg/",
        ".gitattributes", ".gitmodules", ".gitconfig", ".gitkeep",
    ],
    # Caches, dependencies, and build-output directories.
    "generated": [
        "__pycache__/",
        ".venv/", "venv/", "node_modules/",
        ".tox/", ".pytest_cache/", ".mypy_cache/", ".ruff_cache/",
        ".nyc_output/", ".coverage/",
        ".cache/", ".*cache*/", ".npm/", ".yarn/",
        "/out/", "/dist/", ".pdm-build/",
        ".serverless/", ".serverless*/",
        ".terraform/", ".terraform*/",
        ".vagrant/", ".vagrant*/",
    ],
    # High-churn, low-signal text: lockfiles, minified bundles, sourcemaps,
    # logs, editor/OS cruft, VCS conflict leftovers, and boilerplate meta.
    "noisy": [
        "pdm.lock", "poetry.lock", "Pipfile.lock",
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "*.lock",
        "*.min.js", "*.min.css", "*.map",
        ".dockerignore", ".npmignore", ".prettierignore", ".eslintignore",
        "*.swp", "*.swo", "*.swx", "*.swn", ".DS_Store",
        "*.log", "*.tmp", "*.temp", "*.bak", "*.old", "*.orig", "*.rej",
        "*.mine", "*.prej", "*.wrk", "*.base",
        "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "SECURITY.md",
    ],
}

# Order in which the everyday exclude sets are applied (all on by default).
EVERYDAY_EXCLUDE_SET_ORDER = ("binary", "vcs", "generated", "noisy")

# Secrets and credentials. Applied *after* user --glob patterns (the "last
# word"), so a broad include like `--glob '**'` cannot re-expose them. Opt in
# explicitly with --include-sensitive.
SENSITIVE_EXCLUDES: list[str] = [
    ".env", ".env.*", ".envrc", ".envrc.*",
    "*.pem", "*.key", "*.p12", "*.pfx", "*.ppk", "*.keystore",
    "id_rsa", "id_dsa", "id_ecdsa", "id_ed25519",
    ".npmrc", ".pypirc", ".netrc", ".htpasswd",
]

IGNORE_MIME_SUPERTYPES = [
    "application",
    "audio",
    "font",
    "image",
    "video",
]

# overrides IGNORE_MIME_SUPERTYPES
OK_MIMETYPES = [
    "application/json",
    "application/manifest+json",
    "application/postscript",
    "application/vnd.adobe.xdp+xml",
    "application/xml",
    "application/xaml+xml",
    "application/opensearchdescription+xml",
    "application/javascript",
    "application/xhtml+xml",
    "Application/xml",
    "application/xml-dtd",
    "application/xslt+xml",
    "application/x-javascript",
    "application/x-sh",
    "application/x-tex",
    "application/x-latex",
    "string",
]

FILEEXT_TO_MDLANG = {
    ".1": "troff",
    ".2": "troff",
    ".3": "troff",
    ".4": "troff",
    ".4th": "forth",
    ".5": "troff",
    ".6": "troff",
    ".7": "troff",
    ".8": "troff",
    ".9": "troff",
    ".ad": "asciidoc",
    ".adoc": "asciidoc",
    ".apl": "apl",
    ".asc": "asciiarmor",
    ".asciidoc": "asciidoc",
    ".asn": "asn1",
    ".asn1": "asn1",
    ".b": "brainfuck",
    ".babel": "json",
    ".babelcache": "json",
    ".babelignore": "json",
    ".babelrc": "json",
    ".bash": "bash",
    ".bash_aliases": "bash",
    ".bash_functions": "bash",
    ".bash_history": "bash",
    ".bash_login": "bash",
    ".bash_logout": "bash",
    ".bash_profile": "bash",
    ".bashrc": "bash",
    ".bat": "batch",
    ".bf": "brainfuck",
    ".bib": "latex",
    ".build": "python",
    ".bzl": "python",
    ".c": "c",
    ".c++": "cpp",
    ".cabal": "haskell",
    ".cargo": "rust",
    ".cc": "cpp",
    ".cfg": "ini",
    ".cgi": "perl",
    ".cjs": "javascript",
    ".cl": "lisp",
    ".clj": "clojure",
    ".cljc": "clojure",
    ".cljs": "clojure",
    ".cljx": "clojure",
    ".cls": "latex",
    ".cmake": "cmake",
    ".cmake.in": "cmake",
    ".cmakecache": "cmake",
    ".cmd": "batch",
    ".cob": "cobol",
    ".coffee": "coffeescript",
    ".conf": "ini",
    ".cpp": "cpp",
    ".cpy": "cobol",
    ".cql": "sql",
    ".cr": "crystal",
    ".crt": "text",
    ".cs": "csharp",
    ".csproj": "xml",
    ".csr": "text",
    ".css": "css",
    ".csv": "csv",
    ".cxx": "cpp",
    ".cyp": "cypher",
    ".cypher": "cypher",
    ".d": "d",
    ".dart": "clike",
    ".diff": "diff",
    ".dockerignore": "ini",
    ".dsp": "xml",
    ".dsw": "xml",
    ".dtd": "dtd",
    ".dtx": "latex",
    ".dyalog": "apl",
    ".dyl": "dylan",
    ".dylan": "dylan",
    ".e": "eiffel",
    ".ecl": "ecl",
    ".editorconfig": "ini",
    ".edn": "clojure",
    ".el": "lisp",
    ".elm": "elm",
    ".env.example": "ini",
    ".env.sample": "ini",
    ".envrc.example": "ini",
    ".envrc.sample": "ini",
    ".erl": "erlang",
    ".erlang": "erlang",
    ".es": "erlang",
    ".escript": "erlang",
    ".eslint": "json",
    ".eslintcache": "json",
    ".eslintignore": "ini",
    ".eslintrc": "json",
    ".f": "fortran",
    ".f77": "fortran",
    ".f90": "fortran",
    ".f95": "fortran",
    ".factor": "factor",
    ".feature": "gherkin",
    ".fish": "fish",
    ".fishrc": "fish",
    ".flow": "json",
    ".flowconfig": "ini",
    ".for": "fortran",
    ".forth": "forth",
    ".fs": "fsharp",
    ".fsi": "fsharp",
    ".fsproj": "xml",
    ".fsx": "fsharp",
    ".fth": "forth",
    ".gemspec": "ruby",
    ".git": "ini",
    ".gitattributes": "ini",
    ".gitconfig": "ini",
    ".gitignore": "ini",
    ".gitkeep": "ini",
    ".gitmodules": "ini",
    ".gn": "ninja",
    ".gninja": "ninja",
    ".go": "go",
    ".gql": "graphql",
    ".gradle": "groovy",
    ".graphql": "graphql",
    ".groovy": "groovy",
    ".gss": "css",
    ".gvimrc": "vim",
    ".h": "cpp",
    ".h++": "cpp",
    ".handlebars": "html",
    ".haskell": "haskell",
    ".hbs": "html",
    ".hg": "ini",
    ".hgignore": "ini",
    ".hh": "cpp",
    ".hie": "haskell",
    ".hpp": "cpp",
    ".hrl": "erlang",
    ".hs": "haskell",
    ".htaccess": "apache",
    ".htm": "html",
    ".html": "html",
    ".hx": "haxe",
    ".hxml": "haxe",
    ".hxx": "cpp",
    ".in": "properties",
    ".ini": "ini",
    ".ino": "cpp",
    ".ins": "latex",
    ".intr": "dylan",
    ".irb": "ruby",
    ".j2": "jinja2",
    ".java": "java",
    ".jinja": "jinja2",
    ".jinja2": "jinja2",
    ".jl": "julia",
    ".js": "javascript",
    ".jse": "javascript",
    ".json": "json",
    ".jsonld": "javascript",
    ".jsx": "javascript",
    ".key": "text",
    ".ksh": "shell",
    ".kt": "kotlin",
    ".latex": "latex",
    ".less": "css",
    ".lhs": "haskell",
    ".lisp": "lisp",
    ".ls": "livescript",
    ".ltx": "latex",
    ".lua": "lua",
    ".m": "clike",
    ".make": "makefile",
    ".makefile": "makefile",
    ".map": "json",
    ".markdown": "markdown",
    ".mbox": "mbox",
    ".md": "markdown",
    ".mjs": "javascript",
    ".mk": "makefile",
    ".mkd": "markdown",
    ".mkfile": "makefile",
    ".ml": "mllike",
    ".mli": "mllike",
    ".mll": "mllike",
    ".mly": "mllike",
    ".mm": "clike",
    ".mo": "modelica",
    ".mps": "mumps",
    ".msc": "mscgen",
    ".mscgen": "mscgen",
    ".mscin": "mscgen",
    ".msgenny": "mscgen",
    ".nb": "mathematica",
    ".ninja": "ninja",
    ".npmignore": "ini",
    ".nq": "ntriples",
    ".nsh": "nsis",
    ".nsi": "nsis",
    ".nt": "ntriples",
    ".nut": "clike",
    ".nvim": "vim",
    ".nvimrc": "vim",
    ".oz": "oz",
    ".p": "pascal",
    ".pas": "pascal",
    ".patch": "diff",
    ".pem": "text",
    ".pgp": "asciiarmor",
    ".php": "php",
    ".php3": "php",
    ".php4": "php",
    ".php5": "php",
    ".php7": "php",
    ".phtml": "php",
    ".pig": "pig",
    ".pl": "perl",
    ".pls": "sql",
    ".pm": "perl",
    ".po": "gettext",
    ".pod": "perl",
    ".podspec": "ruby",
    ".pot": "gettext",
    ".pp": "puppet",
    ".prettier": "json",
    ".prettiercache": "json",
    ".prettierignore": "json",
    ".prettierrc": "json",
    ".pro": "idl",
    ".properties": "ini",
    ".proto": "protobuf",
    ".ps1": "powershell",
    ".psd1": "powershell",
    ".psm1": "powershell",
    ".pxd": "python",
    ".pxi": "python",
    ".py": "python",
    ".pyw": "python",
    ".pyx": "python",
    ".q": "q",
    ".r": "r",
    ".rake": "ruby",
    ".rb": "ruby",
    ".rbw": "ruby",
    ".rq": "sparql",
    ".rs": "rust",
    ".s": "gas",
    ".sas": "sas",
    ".scala": "scala",
    ".scm": "scheme",
    ".scss": "css",
    ".sh": "bash",
    ".sieve": "sieve",
    ".sig": "asciiarmor",
    ".siv": "sieve",
    ".sln": "xml",
    ".sparql": "sparql",
    ".spec": "rpm",
    ".sql": "sql",
    ".ss": "scheme",
    ".st": "smalltalk",
    ".sty": "latex",
    ".styl": "stylus",
    ".svg": "xml",
    ".swift": "swift",
    ".swiftmodule": "swift",
    ".swiftplayground": "swift",
    ".swiftsource": "swift",
    ".swiftui": "swift",
    ".t": "perl",
    ".tcl": "tcl",
    ".tex": "latex",
    ".text": "stex",
    ".textile": "textile",
    ".thor": "ruby",
    ".toml": "toml",
    ".ts": "typescript",
    ".tsv": "csv",
    ".tsx": "typescript",
    ".ttcn": "ttcn",
    ".ttcn3": "ttcn",
    ".ttcnpp": "ttcn",
    ".ttl": "turtle",
    ".v": "verilog",
    ".vb": "vb",
    ".vba": "vbscript",
    ".vbe": "vbscript",
    ".vbs": "vbscript",
    ".vbscript": "vbscript",
    ".vhd": "vhdl",
    ".vhdl": "vhdl",
    ".vim": "vim",
    ".vimrc": "vim",
    ".vtl": "velocity",
    ".wast": "wast",
    ".wat": "wast",
    ".webidl": "webidl",
    ".wl": "mathematica",
    ".wls": "mathematica",
    ".wsf": "xml",
    ".xml": "xml",
    ".xquery": "xquery",
    ".xsd": "xml",
    ".xsl": "xml",
    ".xu": "mscgen",
    ".xy": "xquery",
    ".yaml": "yaml",
    ".yarnignore": "ini",
    ".yml": "yaml",
    ".ys": "yacas",
    ".z80": "z80",
    ".zsh": "bash",
    ".zshrc": "bash",
}


# Common files worth including in --baseline=known that lack a recognised
# extension (or whose name, not extension, carries the signal).
_KNOWN_GOOD_NAMED = [
    "README", "README.*", "readme", "readme.*",
    "LICENSE", "LICENSE.*", "LICENCE", "LICENCE.*", "COPYING", "COPYING.*",
    "AUTHORS", "CONTRIBUTORS", "NOTICE", "CHANGELOG", "CHANGELOG.*", "CHANGES",
    "Makefile", "GNUmakefile", "makefile",
    "Dockerfile", "Dockerfile.*", "*.dockerfile", "Containerfile",
    "Procfile", "Rakefile", "Gemfile", "Gemfile.*", "Vagrantfile",
    "Brewfile", "Justfile", "justfile",
    ".gitignore", ".editorconfig",
]


def _known_good_includes() -> list[str]:
    """Allowlist of 'known-good' text patterns for --baseline=known.

    Derived from the recognised source-file extensions plus a curated set of
    common extension-less filenames. Users can add more via --glob.
    """
    ext_globs = sorted({f"*{ext}" for ext in FILEEXT_TO_MDLANG})
    return list(_KNOWN_GOOD_NAMED) + ext_globs


KNOWN_GOOD_INCLUDES: list[str] = _known_good_includes()
